### ISSUE TITLE
[Android] Lottie crash at start  

### ISSUE THREAD

**Issue by hadibeiki** [react-native-community/lottie-react-native#542]
### Description

when app start on android studio emulator close immediately...
i tested without Lottie and it work perfectly

### Versions
React Native v:0.60.5
"lottie-react-native": "^3.0.4",

and with this version :

React Native v:0.60.5
"lottie-react-native": "^3.1.0",

what should i do!!!?

`import React, { Fragment } from 'react';
import {
  View,
  Text,
} from 'react-native';
import LottieView from 'lottie-react-native';
export default class App extends React.Component {
  render() {
    return (
      <View style={{ width: 100, height: 100 }}>
        
        <Text>Atefe Dehghan</Text>
        <LottieView source={require('./Ali/treeanimation02.json')} autoPlay loop />
      </View>
    );
  }
};
`

**Comment by Vitalik7** [comment]
same issue

**Comment by jegathispandi** [comment]
Same issue. anyone help me to fix this issue

**Comment by ThakurKarthik** [comment]
I am facing the same issue.App installs fine but crashes when trying to render LottieView.

**Versions :**
```
    "lottie-ios": "^3.0.3",
    "lottie-react-native": "^3.1.0",
    "react": "16.9.0",
    "react-native": "0.60.5",
```
Running on _Motorola G4 Plus_ Android version 8.1

**Comment by ThakurKarthik** [comment]
I was able to resolve my issue by going through this comment https://github.com/react-native-community/lottie-react-native/issues/153#issuecomment-525621137

**Comment by thanhnha121** [comment]
I resolved my problem by:
Download the most popular Lottie file at https://lottiefiles.com/ (ex https://lottiefiles.com/201-simple-loader) then replaced the existing file, and it worked.
Looking at the file content, I saw that version of it is "v":"4.6.3".
So I downgrade Bodymowin Extension, version back to 4.13.0 (you can download it here https://github.com/airbnb/lottie-web/releases/tag/v4.13.0) then regenerated json file and it worked!
I thought that Lottie-react-native got some troubles with json file at 5. x versions.

Hope this helps!

**Comment by parth-choudhary** [comment]
To resolve this, create a native assets folder (for android `app/src/main/assets`).
Place your images inside a folder in this assets folder (like `app/src/main/assets/images`).

Now in the `LottieView` add a prop `imageAssetsFolder`, that should do it.
Final code: 
`<LottieView source={require('../assets/..some.json')} imageAssetsFolder={'images'} autoPlay  />`

**Comment by akshatraajjs** [comment]
ppagla

**Comment by pOlimgit** [comment]
> To resolve this, create a native assets folder (for android `app/src/main/assets`).
> Place your images inside a folder in this assets folder (like `app/src/main/assets/images`).
> 
> Now in the `LottieView` add a prop `imageAssetsFolder`, that should do it.
> Final code:
> `<LottieView source={require('../assets/..some.json')} imageAssetsFolder={'images'} autoPlay />`

it works!

**Comment by aleksandarbos** [comment]
the issue i had was eps/ai files in AE composition. i've tried `export old json format` in advanced bodymovin settings, but that didn't work either. so i started from simple shapes which seem to be working (so it was due to json incompatibility and something else). took me a whole day to figure it out, finally found a comment which says to convert eps/ai files to shapes by going on `layer -> create -> create shapes from vector layer` https://github.com/airbnb/lottie-web/issues/2121#issuecomment-619163860.

**Comment by diegodsp** [comment]
For me the app crashes only if the json has a 5.5.2 version. 5.5.8 works perfectly.

Using:
"expo": "~45.0.5",
"lottie-ios": "3.2.3",
"lottie-react-native": "5.1.3",
"react": "17.0.2",

**Comment by Buk1m** [comment]
My issue was invalid parsing of a json file. I tried a couple of files from https://lottiefiles.com/ and not a single one worked on Andorid, while on iOS everything was fine. Anyway I "fixed" my files by looking at the crash report in Flipper:

```sh
FATAL EXCEPTION: main

Caused by: com.airbnb.lottie.parser.moshi.JsonDataException: Expected a double but was END_ARRAY at path $.layers[26].shapes[2].c.k[3]

FATAL EXCEPTION: main
Process: host.exp.exponent, PID: 20706
java.lang.IllegalStateException: Unable to parse composition
	at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:74)
	at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:67)
	at com.airbnb.lottie.LottieAnimationView$3.onResult(LottieAnimationView.java:91)
	at com.airbnb.lottie.LottieAnimationView$3.onResult(LottieAnimationView.java:84)
	at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:158)
	at com.airbnb.lottie.LottieTask.access$200(LottieTask.java:27)
	at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:133)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:241)
	at android.os.Looper.loop(Looper.java:358)
	at android.app.ActivityThread.main(ActivityThread.java:8114)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: com.airbnb.lottie.parser.moshi.JsonDataException: Expected a double but was END_ARRAY at path $.layers[26].shapes[2].c.k[3]
	at com.airbnb.lottie.parser.moshi.JsonUtf8Reader.nextDouble(JsonUtf8Reader.java:686)
	at com.airbnb.lottie.parser.ColorParser.parse(ColorParser.java:23)
	at com.airbnb.lottie.parser.ColorParser.parse(ColorParser.java:10)
	at com.airbnb.lottie.parser.KeyframeParser.parseStaticValue(KeyframeParser.java:180)
	at com.airbnb.lottie.parser.KeyframeParser.parse(KeyframeParser.java:70)
	at com.airbnb.lottie.parser.KeyframesParser.parse(KeyframesParser.java:38)
	at com.airbnb.lottie.parser.AnimatableValueParser.parse(AnimatableValueParser.java:79)
	at com.airbnb.lottie.parser.AnimatableValueParser.parseColor(AnimatableValueParser.java:65)
	at com.airbnb.lottie.parser.ShapeStrokeParser.parse(ShapeStrokeParser.java:56)
	at com.airbnb.lottie.parser.ContentModelParser.parse(ContentModelParser.java:56)
	at com.airbnb.lottie.parser.LayerParser.parse(LayerParser.java:149)
	at com.airbnb.lottie.parser.LottieCompositionMoshiParser.parseLayers(LottieCompositionMoshiParser.java:121)
	at com.airbnb.lottie.parser.LottieCompositionMoshiParser.parse(LottieCompositionMoshiParser.java:87)
	at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSyncInternal(LottieCompositionFactory.java:371)
	at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSync(LottieCompositionFactory.java:364)
	at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:294)
	at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:287)
	at com.airbnb.lottie.LottieCompositionFactory$4.call(LottieCompositionFactory.java:277)
	at com.airbnb.lottie.LottieCompositionFactory$4.call(LottieCompositionFactory.java:274)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

Whenever there was an array that was going out of bounds i just duplicated the last value to fill the missing index. 
Example:

Node at `layers[26].shapes[2].c.k[3]`
```json
	"c": { "a": 0, "k": [0.2745, 0.4275, 0.698], "ix": 4 },
	
	// changed to
	
         "c": { "a": 0, "k": [0.2745, 0.4275, 0.698,  0.698], "ix": 4 },
	
```

I don't know the semantics of those json files so maybe there is a way to tell the parser that there are only 3 numbers, but lowering the `ix` value didn't help.
