### ISSUE TITLE
Execution failed for task ':app:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by upcwangying** [react-native-community/lottie-react-native#618]
### Description

Running the command `react-native run-android`, an error is reported.

[repo](https://github.com/upcwangying/react-native-demo)

```
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1027 file(s) to forward-jetify. Using 6 workers...
info JS server already running.
info Installing the app...

> Task :lottie-react-native:compileDebugJavaWithJavac

> Task :react-native-gesture-handler:compileDebugJavaWithJavac

> Task :react-native-reanimated:compileDebugJavaWithJavac

> Task :react-native-screens:compileDebugJavaWithJavac

> Task :react-native-webview:compileDebugJavaWithJavac

> Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
148 actionable tasks: 123 executed, 25 up-to-date
注: /Users/ying/workspace/RNProjects/ReactNativeDemo/node_modules/lottie-react-native/src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java使用盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: /Users/ying/workspace/RNProjects/ReactNativeDemo/node_modules/lottie-react-native/src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java使用经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
注: /Users/ying/workspace/RNProjects/ReactNativeDemo/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewanager.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
注: /Users/ying/workspace/RNProjects/ReactNativeDemo/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: /Users/ying/workspace/RNProjects/ReactNativeDemo/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
注: /Users/ying/workspace/RNProjects/ReactNativeDemo/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java使用或覆盖了已。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: /Users/ying/workspace/RNProjects/ReactNativeDemo/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
/Users/ying/workspace/RNProjects/ReactNativeDemo/android/app/src/main/java/com/reactnativegallerydemo/MainApplication.java:19: 错误: 找不到符号
          return BuildConfig.DEBUG;
                 ^
  符号: 变量 BuildConfig
/Users/ying/workspace/RNProjects/ReactNativeDemo/android/app/src/main/java/com/reactnativegallerydemo/MainApplication.java:55: 错误: 找不到符号
    if (BuildConfig.DEBUG) {
        ^
  符号:   变量 BuildConfig
  位置: 类 MainApplication
/Users/ying/workspace/RNProjects/ReactNativeDemo/android/app/src/main/java/com/reactnativegallerydemo/MainApplication.java:55: 错误: 非法的类型开始
    if (BuildConfig.DEBUG) {
       ^
3 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
注: /Users/ying/workspace/RNProjects/ReactNativeDemo/node_modules/lottie-react-native/src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java使用盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: /Users/ying/workspace/RNProjects/ReactNativeDemo/node_modules/lottie-react-native/src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java使用经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
注: /Users/ying/workspace/RNProjects/ReactNativeDemo/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewanager.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
注: /Users/ying/workspace/RNProjects/ReactNativeDemo/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: /Users/ying/workspace/RNProjects/ReactNativeDemo/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
注: /Users/ying/workspace/RNProjects/ReactNativeDemo/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: /Users/ying/workspace/RNProjects/ReactNativeDemo/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
/Users/ying/workspace/RNProjects/ReactNativeDemo/android/app/src/main/java/com/reactnativegallerydemo/MainApplication.java:19: 错误: 找不到符号
          return BuildConfig.DEBUG;
                 ^
  符号: 变量 BuildConfig
/Users/ying/workspace/RNProjects/ReactNativeDemo/android/app/src/main/java/com/reactnativegallerydemo/MainApplication.java:55: 错误: 找不到符号
    if (BuildConfig.DEBUG) {
        ^
  符号:   变量 BuildConfig
  位置: 类 MainApplication
/Users/ying/workspace/RNProjects/ReactNativeDemo/android/app/src/main/java/com/reactnativegallerydemo/MainApplication.java:55: 错误: 非法的类型开始
    if (BuildConfig.DEBUG) {
       ^
3 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (/Users/ying/workspace/RNProjects/ReactNativeDemo/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/Users/ying/workspace/RNProjects/ReactNativeDemo/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:179:41)
    at then.result (/Users/ying/workspace/RNProjects/ReactNativeDemo/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:133:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Versions

`npm version`:  6.14.2.

**Comment by ArijeetG** [comment]
How did you make this work

**Comment by ArijeetG** [comment]
nevermind
